name: CI/CD vagtplan-frontend

on:
  push:
    branches:
      - main
    paths:
      - "vagtplan_frontend/**"
      - ".github/workflows/ci-cd_vagtplan-frontend.yml"

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - "vagtplan_frontend/**"
      - ".github/workflows/ci-cd_vagtplan-frontend.yml"

jobs:
  build_and_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Test Job

    defaults:
      run:
        working-directory: ./vagtplan_frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Vite project
        run: npm run build

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: PR Closed â€” no deployment required on Render
        run: echo "Pull request closed. No cleanup needed for Render."
